### ISSUE TITLE
请问一下为什么terminus主站上的信息没更新？

### ISSUE THREAD

**Issue by vinylalbum** [Gnothi-Seauton/Not-exist-in-douban#2]
我看您这更新了好多，但是https://terminus2049.github.io/Not-exist-in-douban/上为什么就没变化呢？谢谢，本人也很想为这个项目做贡献，请不吝赐教。

**Comment by Gnothi-Seauton** [comment]
抱歉，本项目是fork的项目，意为在原基础上工作，而没有再pull去的打算（总体选取的策略也有所不同）。无论如何，欢迎贡献
